### ISSUE TITLE
include discourse map in other website eg via iframe 

### ISSUE THREAD

**Issue by jacobia** [paviliondev/discourse-locations#43]
we had a map in our forum (https://agora.degrowth.net/c/events/global-degrowth-day-2019/l/map) which we wanted to display in a website but this was not possible. We had to use a screenshot instead. It would be very useful to be able to directly include it.

**Comment by ManUtopiK** [comment]
@jacobia I like degrowth movement :)
I worked to similar map integration, and we have made a vue.js page that fetch all gelocated topics of our discourse platform. Just created [a topic on your disourse](https://agora.degrowth.net/t/discourse-locations-plugin/737).

**Comment by merefield** [comment]
Discourse will not iframe well as is a SPA.  This is outside of the scope of this plugin.  Do as you need to using the API and third party frameworks.
