### ISSUE TITLE
Can't add locations after created topics

### ISSUE THREAD

**Issue by pokapow** [paviliondev/discourse-locations#45]
We can't add locations to topics still created. Is it normal or does options exists about it (don't find it ...) ?

In fact we can't edit any location once created... Even Admin.

**Comment by ManUtopiK** [comment]
Also, once topic is saved, we can't edit location!

**Comment by angusmcleod** [comment]
@pokapow @ManUtopiK You can edit the location by editing the first post in the topic. 

<img width="422" alt="Screenshot at Feb 26 19-53-07" src="https://user-images.githubusercontent.com/5931623/75328227-c84b2b00-58d1-11ea-9bca-833a00f3070e.png">


Ideally you would be able to edit it in the "Topic edit" area as well. Will try to find time to add that, but in the meantime, it's definitely possible to edit the location via the first pot.
