### ISSUE TITLE
Could not find module I18n (stable discourse branch)

### ISSUE THREAD

**Issue by papimla** [paviliondev/discourse-locations#49]
I upgraded today to discourse 2.4.4 (using the stable branch) and it pulled the [latest commit](https://github.com/paviliondev/discourse-locations/commit/6fd0979ebd0d136d3feb4349b5b280ed239ebf43) which [broke our discourse instance](https://meta.discourse.org/t/just-updated-2-4-4-getting-429-errors-in-firefox-chromium/153064/2) because of:

> Error: Could not find module I18n imported from discourse/plugins/discourse-locations/discourse/lib/location-utilities

It would be great if you could fix this issue so we can re-enable the plugin.

Thanks for your work on this very useful plugin !

**Comment by angusmcleod** [comment]
Hey, this plugin tracks the tests-passed branch of Discourse, as that is the branch Discourse puts all sites on by default so most users of the plugin are on it. We don't currently maintain a version of the plugin on Discourse's stable branch, though we may do in the future. If you need to track the stable branch you can fork the plugin and maintain it at a specific commit, pulling in new commits when stable is updated. For further info on the status of this plugin and the current versionf of Discourse see: try.thepavilion.io/c/locations

**Comment by papimla** [comment]
Thanks for the information. We don't have the resources to maintain a stable branch of the plugin. But I understand perfectly that **you** also don't have the resources to do the same :smile:

What about we leave this issue open until the stable branch catches up? It may save some time to others running into the same problem.

**Comment by papimla** [comment]
Now that 2.5.0 was released, this issue is no longer relevant and can be closed.
